apiVersion: v1
kind: Secret
metadata:
    name: kafka-cluster-secrets
    namespace: {{ .Values.namespace }}
type:
    Opaque

stringData:
    KAFKA_CONTROLLER_UUIDs: {{ .Values.controller_uuids }}
    KAFKA_CLUSTER_ID: {{ .Values.cluster_id }}
