apiVersion: v1
kind: Secret
metadata:
    name: mongo-cluster-secrets
    namespace: {{ .Values.namespace }}
type:
    Opaque

data:
    mongo-secret-key: {{ .Values.secret_key }}
    mongo-db-user: {{ .Values.db_user }}
    mongo-db-password: {{ .Values.db_secret }}