# Names
appName: nginx-app

# Namespace
namespace: nginx-app-ns

configMapName: nginx-config

# Replicas
replicas: 3

# Labels:
labels:
    custom:
        app: 'Values.appName'

    kubernetes:
        io:
            app: 'Values.appName'
            component: db
            instance: development

# Pod Settings
pod:
    image: nginx:stable-perl
    containerName: nginx-container
    port:
        number: 80
        forward_number: 80
        target: nginx-port
        service_name: http
    port_debug:
        number: 9229
        forward_number: 9229
        target: debug-port
        service_name: debug
    resources:
        enabled: false
        requests:
            cpu: '1'
            memory: '2Gi'
        limits:
            cpu: '2'
            memory: '4Gi'

# Service settings
service:
    name: nginx-app-service

services:
    app:
        protocol: 'http'
        serviceName: 'app-service'
        namespace: 'authentication-app'
        port: 80

nginx:
    settings:
        user: nginx
        worker_processes: auto
    events:
        worker_connections: 1024
    paths:
        error_log: /var/log/nginx/error.log
        access_log: /var/log/nginx/access.log
        dir_path: /etc/nginx
        nginx_dir_path: /etc/nginx/includes
        server_ports: 'construct[Values.nginx.paths.nginx_dir_path, /ports.conf]'
        server_locations: 'construct[Values.nginx.paths.nginx_dir_path, /locations.conf]'
        mime_types: 'construct[Values.nginx.paths.dir_path, /mime.types]'
        pid: /run/nginx.pid
        stream: 'construct[Values.nginx.paths.nginx_dir_path, /stream.conf]'
    types:
        default: application/octet-stream
    server:
        ports:
            - 80
            - 9229
        locations:
            - path: /
              proxy_pass: 'construct[Values.services.app.protocol, ://, Values.services.app.serviceName, ., Values.services.app.namespace, ., svc.cluster.local:, Values.services.app.port]'
              proxy_pass_debug: 'construct[Values.services.app.serviceName, ., Values.services.app.namespace, ., svc.cluster.local:, Values.services.app.port_debug]'
              proxy_set_headers:
                  - Host $host
                  - X-Real-IP $remote_addr
