# DNS = <POD_NAME>.<SERVICE_NAME>.<NAMESPACE>.svc.cluster.local

# Define the namespace
apiVersion: v1
kind: Namespace
metadata:
    name: authentication

---
# Define the secrets
apiVersion: v1
kind: Secret
metadata:
    name: kafka-cluster-secrets
    namespace: authentication
type:
    Opaque
    # KAFKA_CLUSTER_ID: # openssl rand -base64 20 | base64
    # KAFKA_CLUSTER_ID: # ./opt/kafka/bin/kafka-storage.sh random-uuid | base64

    #KAFKA_CONTROLLER_UUIDs # head /dev/urandom | tr -dc a-z0-9 | head -c 16 | base64 | base64
    # ./opt/kafka/bin/kafka-storage.sh random-uuid | base64

stringData:
    KAFKA_CONTROLLER_UUIDs: 1@22Mwt-tASVSZxlQnuPTCQA,2@WZnw9fvtTnqzCZkjvTJGdQ,3@iXIj14pXQauwNs4PVTQXiQ
    KAFKA_CLUSTER_ID: r74ZFNCqQNCRygvhydm0pw
