#!/bin/sh

set -e

generate_broker_server_file() {
    if [ "$KAFKA_PROCESS_ROLES" = "broker" ]; then
        sed -e "s#((KAFKA_NODE_ID))#$KAFKA_NODE_ID#g" \
            -e "s#((KAFKA_LOG_DIR))#$KAFKA_LOG_DIR#g" \
            -e "s#((KAFKA_LISTENERS))#$KAFKA_LISTENERS#g" \
            -e "s#((KAFKA_PROCESS_ROLES))#$KAFKA_PROCESS_ROLES#g" \
            -e "s#((KAFKA_CONTROLLER_LISTENER_NAMES))#$KAFKA_CONTROLLER_LISTENER_NAMES#g" \
            -e "s#((KAFKA_CLUSTER_ID))#$KAFKA_CLUSTER_ID#g" \
            -e "s#((KAFKA_CONTROLLER_QUORUM_VOTERS))#$KAFKA_CONTROLLER_QUORUM_VOTERS#g" \
            -e "s#((KAFKA_ADVERTISED_LISTENERS))#$KAFKA_ADVERTISED_LISTENERS#g" \
            -e "s#((KAFKA_CONTROLLER_QUORUM_BOOTSTRAP_SERVERS))#$KAFKA_CONTROLLER_QUORUM_BOOTSTRAP_SERVERS#g" \
            -e "s#((KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR))#${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}#g" \
            -e "s#((KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR))#${KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR}#g" \
            -e "s#((KAFKA_TRANSACTION_STATE_LOG_MIN_ISR))#${KAFKA_TRANSACTION_STATE_LOG_MIN_ISR}#g" \
            -e "s#((KAFKA_NUM_NETWORK_THREADS))#${KAFKA_NUM_NETWORK_THREADS}#g" \
            -e "s#((KAFKA_NUM_IO_THREADS))#${KAFKA_NUM_IO_THREADS}#g" \
            -e "s#((KAFKA_SOCKET_SEND_BUFFER_BYTES))#${KAFKA_SOCKET_SEND_BUFFER_BYTES}#g" \
            -e "s#((KAFKA_RECIEVE_BUFFER_BYTES))#${KAFKA_RECIEVE_BUFFER_BYTES}#g" \
            -e "s#((KAFKA_REQUEST_MAX_BYTES))#${KAFKA_REQUEST_MAX_BYTES}#g" \
            -e "s#((KAFKA_NUM_PARTITIONS))#${KAFKA_NUM_PARTITIONS}#g" \
            -e "s#((KAFKA_RECOVERY_THREADS_PER_DATA_DIR))#${KAFKA_RECOVERY_THREADS_PER_DATA_DIR}#g" \
            -e "s#((KAFKA_SHARE_COORDINATOR_STATE_TOPIC_REPLICATION_FACTOR))#${KAFKA_SHARE_COORDINATOR_STATE_TOPIC_REPLICATION_FACTOR}#g" \
            -e "s#((KAFKA_SHARE_COORDINATOR_STATE_TOPIC_MIN_ISR))#${KAFKA_SHARE_COORDINATOR_STATE_TOPIC_MIN_ISR}#g" \
            -e "s#((KAFKA_RETENTION_HOURS))#${KAFKA_RETENTION_HOURS}#g" \
            -e "s#((KAFKA_RETENTION_CHECK_INTERVAL_MS))#${KAFKA_RETENTION_CHECK_INTERVAL_MS}#g" \
            -e "s#((KAFKA_LOG_SEGMENT_BYTES))#${KAFKA_LOG_SEGMENT_BYTES}#g" \
            "$USER_CONFIG_DIR/commando/broker.properties" \
            > "$USER_CONFIG_DIR/server.properties"
    fi
}