#!/bin/sh

set -e

debug() {
    if [ -n "$DEBUG" ]; then

        print_yellow "KAFKA_NODE_ID: ${KAFKA_NODE_ID}" 1
        print_yellow "KAFKA_LISTENERS: ${KAFKA_LISTENERS}" 1
        print_yellow "KAFKA_PROCESS_ROLES: ${KAFKA_PROCESS_ROLES}" 1
        print_yellow "KAFKA_CONTROLLER_LISTENER_NAMES: ${KAFKA_CONTROLLER_LISTENER_NAMES}" 1
        print_yellow "KAFKA_CLUSTER_ID: ${KAFKA_CLUSTER_ID}" 1
        print_yellow "KAFKA_CONTROLLER_QUORUM_BOOTSTRAP_SERVERS: ${KAFKA_CONTROLLER_QUORUM_BOOTSTRAP_SERVERS}" 1
        print_yellow "KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}" 1
        print_yellow "KAFKA_INITIAL_CONTROLLERS: ${KAFKA_INITIAL_CONTROLLERS}" 1
        print_yellow "KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR :${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}" 1
        print_yellow "KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR :${KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR}" 1
        print_yellow "KAFKA_TRANSACTION_STATE_LOG_MIN_ISR :${KAFKA_TRANSACTION_STATE_LOG_MIN_ISR}" 1
        print_yellow "KAFKA_NUM_NETWORK_THREADS :${KAFKA_NUM_NETWORK_THREADS}" 1
        print_yellow "KAFKA_NUM_IO_THREADS :${KAFKA_NUM_IO_THREADS}" 1
        print_yellow "KAFKA_SOCKET_SEND_BUFFER_BYTES :${KAFKA_SOCKET_SEND_BUFFER_BYTES}" 1
        print_yellow "KAFKA_RECIEVE_BUFFER_BYTES :${KAFKA_RECIEVE_BUFFER_BYTES}" 1
        print_yellow "KAFKA_REQUEST_MAX_BYTES :${KAFKA_REQUEST_MAX_BYTES}" 1
        print_yellow "KAFKA_NUM_PARTITIONS :${KAFKA_NUM_PARTITIONS}" 1
        print_yellow "KAFKA_RECOVERY_THREADS_PER_DATA_DIR :${KAFKA_RECOVERY_THREADS_PER_DATA_DIR}" 1
        print_yellow "KAFKA_SHARE_COORDINATOR_STATE_TOPIC_REPLICATION_FACTOR :${KAFKA_SHARE_COORDINATOR_STATE_TOPIC_REPLICATION_FACTOR}" 1
        print_yellow "KAFKA_SHARE_COORDINATOR_STATE_TOPIC_MIN_ISR :${KAFKA_SHARE_COORDINATOR_STATE_TOPIC_MIN_ISR}" 1
        print_yellow "KAFKA_RETENTION_HOURS :${KAFKA_RETENTION_HOURS}" 1
        print_yellow "KAFKA_RETENTION_CHECK_INTERVAL_MS :${KAFKA_RETENTION_CHECK_INTERVAL_MS}" 1
        print_yellow "KAFKA_LOG_SEGMENT_BYTES :${KAFKA_LOG_SEGMENT_BYTES}" 1
        print_yellow "KAFKA_CONTROLLER_QUORUM_VOTERS :${KAFKA_CONTROLLER_QUORUM_VOTERS}" 1

        cat "$USER_CONFIG_DIR/server.properties"
    fi
}
