apiVersion: v1
kind: Secret
metadata:
    name: nginx-secrets
    namespace: '{{ .Values.namespace }}'
type: Opaque

data:
    server.crt: '{{ .Values.server_crt }}'
    server.key: '{{ .Values.server_key }}'
