apiVersion: v1
kind: Secret
metadata:
    name: start-point-secrets
    namespace: '{{ .Values.namespace }}'
type: Opaque

data:
    mongodb_secret_key: '{{ .Values.mongodb_secret_key }}'
    mongodb_db_user: '{{ .Values.mongodb_db_user }}'
    mongodb_db_secret: '{{ .Values.mongodb_db_secret }}'
