apiVersion: v1
kind: Service
metadata:
    name: '{{ .Values.service }}'
    namespace: '{{ .Values.namespace }}'
spec:
    # prettier-ignore
    selector: {{- include "global.commonMetadata" . | nindent 8 }}
    ports:
        - name: "{{ .Values.pod.port.service_name }}"
          # prettier-ignore
          
        #   Forwarfing the app port via service to 80; if 3000 is the app, the service uses 80 to forward it
          port: {{ .Values.pod.port.service_forward_number }}

          # prettier-ignore
          # This is the port of the app | pod
          targetPort: {{ trunc 15 .Values.pod.port.target | lower | quote }}

        - name: "{{ .Values.pod.port_debug.service_name }}"
          # prettier-ignore
          
        #   Forwarfing the app port via service to 80; if 3000 is the app, the service uses 80 to forward it
          port: {{ .Values.pod.port_debug.service_forward_number }}

          # prettier-ignore
          # This is the port of the app | pod
          targetPort: {{ trunc 15 .Values.pod.port_debug.target | lower | quote }}

    type: LoadBalancer
