# Define the namespace
apiVersion: v1
kind: Namespace
metadata:
    name: authentication

---
# Define the secrets
apiVersion: v1
kind: Secret
metadata:
    name: mongo-cluster-secrets
    namespace: authentication
type: Opaque
data:
    mongo-secret-key: c21rbWJYZzBzeVlpT0xqRU5aTnZTNHNKbUh3Q0J0bElJK2dSR2NaNmtvWjNRN2lhR05OYkxpU0RDTnkyOFBLbApjbzMwdnoreUZKTmpGT1JpYTQ1YUtsMC9tNzJuZHp6elpCN3NEMkppT01IUVdYdlU3ZU54V2xGOHJKRHlwb24xCnE4UFYwUHdlZ09TeHBaT3VLRStSQ1pJaGYwQktGWnl0Q0VvY0RQTm1KL3IzRk1wa0NyR3RnajZkMjJCd3B0Z1gKQ096bXRyQjdRaE54SkpFR2t2aGZIdWRVVFRDOE13N3psbFlIMkJxblVpNWY3bm9UeTJPQXF1bHdEUDVPa1dVeQpxYXdHZUkvODNhWHhxZDRSQjhaZEdoQ293aDY1aTBOMHhwMFZOOTB1Sit1WCtiMFZqUHpINGlYWG5INWZWQTFaCjJWZnJ4c0grcDArSEVXTDF3L0gvMWZQaVFRelBpczI3V0lVdFlZaHlYT2g4Tmkxd2J4cG1nTmFuc1hpSlNsenMKZDJXLzNwMllrVmFpeTE3MkpUOHovR2k3aFl0U0lraGJqUkhVUkVxVFZhdUFuWG54QlN4RzB2S3ZGVE9uQldFUQpad2U1THpaOHlPZ2x3S2huT0o1eGVjMDkvL0NMeG9NMHR6VnUrY1ZXRkhGME9ZcFVlYXJuVFpmUFNHQVYzWTlMClROKy9XUHVFQ0NQazR1cWp3aFN2MG84WGN4enhaT0pNdk5qNmtMNnJQZ2dXYXMvRG85QjNUbE9WNnRua2ZOeTgKclJWcGdXVWwzK2pjOFdybEtzTW1vRm5wYVhDODlWNUNYQzdZdFRRcXJtd04vNGd1Q3BmSDljdmo1WFVJZ2dtNQp1WTNRYXhWU1dWZ2dwMVV3Unlsa08wTGRYU3pST1ovK1JmQ2RGeUV4bENVPQ==
    mongo-db-user: c3VwZXJhZG1pbg==
    mongo-db-password: c3VwZXJhZG1pbg==