apiVersion: v1
kind: Secret
metadata:
    name: redis-cluster-secrets
    namespace: {{ .Values.namespace }}
type: Opaque

data:
    tls.crt: {{ .Values.crt }}
    tls.key: {{ .Values.key }}
    ca.crt: {{ .Values.ca }}