apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.service.name }}
    namespace: {{ .Values.namespace }}
spec:
    selector:
        {{- include "global.commonMetadata" . | nindent 12 }}
    ports:
      - name: {{ .Values.service.port.name }}
        port: {{ .Values.pod.port.number }}
        targetPort: {{  trunc 15 .Values.pod.port.target | lower | quote }}

      - name: {{ .Values.service.bus_port.name }}
        port: {{ .Values.pod.bus_port.number }}
        targetPort: {{  trunc 15 .Values.pod.bus_port.target | lower | quote }}
    clusterIP: None
