apiVersion: v1
kind: Service
metadata:
    name: '{{ .Values.service.name }}'
    namespace: '{{ .Values.namespace }}'
spec:
    # prettier-ignore
    selector: {{- include "global.commonMetadata" . | nindent 12 }}
    ports:
        - name: "{{ .Values.service.port.name }}"
          # prettier-ignore
          port: {{ .Values.pod.port.number }}
          # prettier-ignore
          targetPort: {{ trunc 15 .Values.pod.port.target | lower | quote }}

        - name: "{{ .Values.service.bus_port.name }}"
          # prettier-ignore
          port: {{ .Values.pod.bus_port.number }}
          # prettier-ignore
          targetPort: {{ trunc 15 .Values.pod.bus_port.target | lower | quote }}
    clusterIP: None
